version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - customer_net

  web:
    image: kigencaleb/customer-order-api:latest
    depends_on:
      - db
    environment:
      DB_NAME: customerdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      AFRICASTALKING_API_KEY: atsk_77abb81641be90244ca457ec487187b402c32af48f4a053c164e440aed7a2b967bfc45be
      AUTH0_M2M_CLIENT_ID: BiFe3tWNabGSz7041CXC8DW9Yu9N68YD
      AUTH0_M2M_CLIENT_SECRET: kJjDF5h1tro8qrjg4cmMyeE3C4P5d4fqQBkZOXB-lozEHigkRQXMqMEZDBm4tYgA
      AUTH0_DOMAIN: dev-vrtbtpvaqaxh54iu.us.auth0.com
      AUTH0_AUDIENCE: https://dev-vrtbtpvaqaxh54iu.us.auth0.com/api/v2/
      ADMIN_API_KEY: 123456721
      AUTH0_API_URL: https://dev-vrtbtpvaqaxh54iu.us.auth0.com/api/v2
      AUTH0_CLIENT_ID: eQjd8fmMQ8jSaoSDoikUmViV7LRoNQXX
      AUTH0_CLIENT_SECRET: 1V6CM2Hn4rsy8WmjFXWcfd5r3AByRggw3_RSmA_W0tMnPvfEXK7jGK3GBOhL345W
      AUTH0_USER_CLIENT_ID: fyjizP3bktUeKQrLa48TgrmsThIYuSSB
      AUTH0_USER_CLIENT_SECRET: IFiwPIg6_xWYPzGVX1EXf9UzdACKsa05VatPWlhHyiCSyKd6rOlP0lmE0f1wiEgJ
      AUTH0_FRONTEND_CLIENT_ID: fyjizP3bktUeKQrLa48TgrmsThIYuSSB
      AUTH0_FRONTEND_CLIENT_SECRET: IFiwPIg6_xWYPzGVX1EXf9UzdACKsa05VatPWlhHyiCSyKd6rOlP0lmE0f1wiEgJ
      JWT_SECRET: dummysavanna
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             gunicorn customer_app.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - customer_net

volumes:
  postgres_data:

networks:
  customer_net:
