"""
Django settings for customer_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o!z_l((b9g(vs9p^c06ud7)^lb%4i(r%1d5bsf+-_o*npv%7^o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]  # Allow all hosts for development purposes


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'customer_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'customer_app.wsgi.application'
CSRF_TRUSTED_ORIGINS = ["http://ec2-18-142-238-98.ap-southeast-1.compute.amazonaws.com"]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AFRICASTALKING_API_KEY= 'atsk_77abb81641be90244ca457ec487187b402c32af48f4a053c164e440aed7a2b967bfc45be'
AFRICASTALKING_SENDER_ID = '77421'
AFRICAS_USERNAME = 'sandbox'

AUTH0_M2M_CLIENT_ID='BiFe3tWNabGSz7041CXC8DW9Yu9N68YD'
AUTH0_M2M_CLIENT_SECRET='kJjDF5h1tro8qrjg4cmMyeE3C4P5d4fqQBkZOXB-lozEHigkRQXMqMEZDBm4tYgA'

AUTH0_DOMAIN='dev-vrtbtpvaqaxh54iu.us.auth0.com'
# https://dev-vrtbtpvaqaxh54iu.us.auth0.com/api/v2/
AUTH0_AUDIENCE='https://dev-vrtbtpvaqaxh54iu.us.auth0.com/api/v2/'
ADMIN_API_KEY = '123456721'
AUTH0_API_URL='https://dev-vrtbtpvaqaxh54iu.us.auth0.com/api/v2'
AUTH0_CLIENT_ID='eQjd8fmMQ8jSaoSDoikUmViV7LRoNQXX'
AUTH0_CLIENT_SECRET='1V6CM2Hn4rsy8WmjFXWcfd5r3AByRggw3_RSmA_W0tMnPvfEXK7jGK3GBOhL345W'
AUTH0_USER_CLIENT_ID = "fyjizP3bktUeKQrLa48TgrmsThIYuSSB"
AUTH0_USER_CLIENT_SECRET = "IFiwPIg6_xWYPzGVX1EXf9UzdACKsa05VatPWlhHyiCSyKd6rOlP0lmE0f1wiEgJ"